### ISSUE TITLE
Models and Tables

### ISSUE THREAD

**Issue by klrosenberg** [klrosenberg/06-23-sinatra-beer#22]
# Beer Rating Archive
## beers

<table>
<tr>
   <th>id (primary key)</th>
   <th>name (text)</th>
   <th>abv (integer)</th>
   <th>beer_type_id (foreign key)</th>
   <th>brewery_id (foreign key)</th>
   <th>avg_rating (integer)</th>
</tr>
<tr>
   <td></td>
   <td></td>
   <td></td>
   <td></td>
   <td></td>
   <td></td>
</tr>
</table>

## breweries

<table>
<tr>
   <th>id (primary key)</th>
   <th>name (text)</th>
</tr>
<tr>
   <td></td>
   <td></td>
</tr>
</table>

## beer_types

<table>
<tr>
   <th>id (primary key)</th>
   <th>name (text)</th>
</tr>
<tr>
   <td></td>
   <td></td>
</tr>
</table>

## users

<table>
<tr>
   <th>id (primary key)</th>
   <th>name (text)</th>
</tr>
<tr>
   <td></td>
   <td></td>
</tr>
</table>

## ratings

<table>
<tr>
   <th>id (primary key)</th>
   <th>user_id (foreign key)</th>
   <th>beer_id (foreign key)</th>
   <th>rating (integer)</th>
</tr>
<tr>
   <td></td>
   <td></td>
   <td></td>
   <td></td>
</tr>
</table>

**Comment by sumeetjain** [comment]
There are a couple minor naming issues. Please do an audit based on https://github.com/omahacodeschool/wiki/blob/master/ruby/naming-things.md
