### ISSUE TITLE
Feedback for Refactoring

### ISSUE THREAD

**Issue by klrosenberg** [klrosenberg/06-23-sinatra-beer#24]

**Comment by sumeetjain** [comment]
- [ ] You're not using your utility method for the table name as often as you could. Example: https://github.com/klrosenberg/06-23-sinatra-beer/blob/master/database_class_methods.rb#L54
- [ ] The code that loops through an array of hashes and makes objects from them is a good candidate for a utility method.
  - [ ] Once you do this, other occurrences of that process can be DRYed up, e.g. [this](JIJIJIJIJIJI)
- [ ] There's enough going on [here](https://github.com/klrosenberg/06-23-sinatra-beer/blob/master/database_class_methods.rb#L41) to warrant splitting it up into many smaller methods. Remember, making smaller methods isn't just to remove repetition – it's also to achieve SRP.
